spring:
  application:
    name: auction
  datasource:
    url: jdbc:postgresql://localhost:5432/auction_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
