spring:
  application:
    name: auction
  datasource:

    url: jdbc:postgresql://localhost:5432/auction_db_4
    username: postgres
    password: 2004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# --- STRIPE CONFIGURATION ---

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_51SlVv4RkaBQILD6AXRqODGdp41UfO94QXQOcfghwraWoZraUb5v4pKE1boqozp5eEGhthRz9f3mLpnpTX0nQZ2lf00EC0BymSa}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51SlVv4RkaBQILD6AyG5PZJbsO71BTsok0R6gdhK5nVsuwlLLUYNwazqfOLxyRGmnXom7E8y9b0ZdO5zUTfgvanoZ00VtvmqTBr}
