spring:
  application:
    name: auction
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-broad-dawn-a1238rlr-pooler.ap-southeast-1.aws.neon.tech/auction?sslmode=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_OL2BxARm7tZn}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# --- STRIPE CONFIGURATION ---

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_51SlVv4RkaBQILD6AXRqODGdp41UfO94QXQOcfghwraWoZraUb5v4pKE1boqozp5eEGhthRz9f3mLpnpTX0nQZ2lf00EC0BymSa}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51SlVv4RkaBQILD6AyG5PZJbsO71BTsok0R6gdhK5nVsuwlLLUYNwazqfOLxyRGmnXom7E8y9b0ZdO5zUTfgvanoZ00VtvmqTBr}
